version: "3.9"
services:
  acme-sh:
    build: .
    image: acme-sh
    tty: true
    stdin_open: true
    container_name: acme-sh
    restart: always
    env_file:
      - .env
    volumes:
      - /volumes/acme/cert:/cert
      - /volumes/acme/home:/root/.acme.sh
    network_mode: host
