version: "3.9"
services:
  acmecf:
    build: .
    image: acmecf
    tty: true
    stdin_open: true
    container_name: acmecf
    restart: always
    env_file:
      - .env
    volumes:
      - /path/to/cert:/acme
    network_mode: host
