version: "3.9"
services:
  acme:
    image: ghcr.io/jerry12122/acme:latest
    tty: true
    stdin_open: true
    container_name: acme
    restart: always
    env_file:
      - .env
    volumes:
      - /path/to/cert:/cert
      - /path/to/home:/root/.acme.sh
    network_mode: host
