name: Build and publish Docker image to GitHub Packages

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: acme
  DOCKER_BUILDKIT: 1

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Change tag to latest
        run: docker tag ghcr.io/${{ github.repository }}:${{ github.sha }} ghcr.io/${{ github.repository }}:latest
        
      - name: Push the Docker image to GitHub Packages
        run: docker push ghcr.io/${{ github.repository }}:latest
        
      - name: Delete Package Versions Keep Latest
        uses: windyakin/delete-package-versions-keep-latest@1.0.2
        with:
          package-name: ghcr.io/${{ github.repository }}
          keep-latest-package-versions: 2
