name: Build and publish Docker image to GitHub Packages

on:
  push:
    branches:
      - release
env:
  IMAGE_NAME: acme
  DOCKER_BUILDKIT: 1

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Save state
        run: echo "version=$(cat VERSION)" >> $GITHUB_ENV

      - name: Build the Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.version }}

      - name: Add latest tag
        run: |
          docker tag ghcr.io/${{ github.repository }}:${{ env.version }} ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest
